// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "../ui.h"

void ui_IOT_S4_screen_init(void)
{
    ui_IOT_S4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IOT_S4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IOT_S4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IOT_S4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S2_Bg_9 = lv_img_create(ui_IOT_S4);
    lv_img_set_src(ui_IMG_S2_Bg_9, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_9, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_9, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_9, -81);
    lv_obj_set_y(ui_IMG_S2_Bg_9, -267);
    lv_obj_set_align(ui_IMG_S2_Bg_9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_S2_Bg_10 = lv_img_create(ui_IOT_S4);
    lv_img_set_src(ui_IMG_S2_Bg_10, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_10, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_10, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_10, 158);
    lv_obj_set_y(ui_IMG_S2_Bg_10, 77);
    lv_obj_set_align(ui_IMG_S2_Bg_10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Add_Device1 = lv_label_create(ui_IOT_S4);
    lv_obj_set_width(ui_Label_Add_Device1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Add_Device1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Add_Device1, 0);
    lv_obj_set_y(ui_Label_Add_Device1, 15);
    lv_obj_set_align(ui_Label_Add_Device1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Add_Device1, "Del Device");
    lv_obj_set_style_text_color(ui_Label_Add_Device1, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Add_Device1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Add_Device1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Add_Device1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Want_to_add1 = lv_label_create(ui_IOT_S4);
    lv_obj_set_width(ui_Label_Want_to_add1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Want_to_add1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Want_to_add1, 0);
    lv_obj_set_y(ui_Label_Want_to_add1, 60);
    lv_obj_set_align(ui_Label_Want_to_add1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Want_to_add1, "Pick the device you want to delete\nOnly Lamp is possible!");
    lv_obj_set_style_text_color(ui_Label_Want_to_add1, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Want_to_add1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Want_to_add1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Want_to_add1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Click_to_Add_Device1 = lv_label_create(ui_IOT_S4);
    lv_obj_set_width(ui_Label_Click_to_Add_Device1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Click_to_Add_Device1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Click_to_Add_Device1, 0);
    lv_obj_set_y(ui_Label_Click_to_Add_Device1, 180);
    lv_obj_set_align(ui_Label_Click_to_Add_Device1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Click_to_Add_Device1, "Click to Del Device");
    lv_obj_set_style_text_color(ui_Label_Click_to_Add_Device1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Click_to_Add_Device1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Click_to_Add_Device1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_Click_to_Add_Device1, lv_color_hex(0xFFDAC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_Click_to_Add_Device1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label_Click_to_Add_Device1, lv_color_hex(0xFFE6DB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Nas1 = lv_label_create(ui_IOT_S4);
    lv_obj_set_width(ui_Label_Nas1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Nas1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Nas1, -90);
    lv_obj_set_y(ui_Label_Nas1, -45);
    lv_obj_set_align(ui_Label_Nas1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Nas1, "Nas/Service");

    ui_Label_Router1 = lv_label_create(ui_IOT_S4);
    lv_obj_set_width(ui_Label_Router1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Router1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Router1, 10);
    lv_obj_set_y(ui_Label_Router1, -45);
    lv_obj_set_align(ui_Label_Router1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Router1, "Router");

    ui_Label_Sound1 = lv_label_create(ui_IOT_S4);
    lv_obj_set_width(ui_Label_Sound1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Sound1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Sound1, 104);
    lv_obj_set_y(ui_Label_Sound1, -45);
    lv_obj_set_align(ui_Label_Sound1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Sound1, "Sound");

    ui_Label_Lamp1 = lv_label_create(ui_IOT_S4);
    lv_obj_set_width(ui_Label_Lamp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Lamp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Lamp1, -90);
    lv_obj_set_y(ui_Label_Lamp1, 88);
    lv_obj_set_align(ui_Label_Lamp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Lamp1, "Lamp");

    ui_Label_Camera1 = lv_label_create(ui_IOT_S4);
    lv_obj_set_width(ui_Label_Camera1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Camera1, LV_SIZE_CONTENT);    /// -155
    lv_obj_set_x(ui_Label_Camera1, 10);
    lv_obj_set_y(ui_Label_Camera1, 88);
    lv_obj_set_align(ui_Label_Camera1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Camera1, "Camera");

    ui_Label_Socket1 = lv_label_create(ui_IOT_S4);
    lv_obj_set_width(ui_Label_Socket1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Socket1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Socket1, 104);
    lv_obj_set_y(ui_Label_Socket1, 88);
    lv_obj_set_align(ui_Label_Socket1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Socket1, "Socket");

    ui_Panel_Return1 = lv_obj_create(ui_IOT_S4);
    lv_obj_set_width(ui_Panel_Return1, 48);
    lv_obj_set_height(ui_Panel_Return1, 48);
    lv_obj_set_x(ui_Panel_Return1, -130);
    lv_obj_set_y(ui_Panel_Return1, -210);
    lv_obj_set_align(ui_Panel_Return1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Return1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Return1 = lv_img_create(ui_Panel_Return1);
    lv_img_set_src(ui_Image_Return1, &ui_img_return_png);
    lv_obj_set_width(ui_Image_Return1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Return1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_Return1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Return1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Return1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Nas1 = lv_obj_create(ui_IOT_S4);
    lv_obj_set_width(ui_Panel_Nas1, 48);
    lv_obj_set_height(ui_Panel_Nas1, 48);
    lv_obj_set_x(ui_Panel_Nas1, -90);
    lv_obj_set_y(ui_Panel_Nas1, -80);
    lv_obj_set_align(ui_Panel_Nas1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Nas1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageNas1 = lv_img_create(ui_Panel_Nas1);
    lv_img_set_src(ui_ImageNas1, &ui_img_service_png);
    lv_obj_set_width(ui_ImageNas1, 48);
    lv_obj_set_height(ui_ImageNas1, 48);
    lv_obj_set_align(ui_ImageNas1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageNas1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageNas1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Router1 = lv_obj_create(ui_IOT_S4);
    lv_obj_set_width(ui_Panel_Router1, 48);
    lv_obj_set_height(ui_Panel_Router1, 48);
    lv_obj_set_x(ui_Panel_Router1, 10);
    lv_obj_set_y(ui_Panel_Router1, -80);
    lv_obj_set_align(ui_Panel_Router1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Router1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageRouter1 = lv_img_create(ui_Panel_Router1);
    lv_img_set_src(ui_ImageRouter1, &ui_img_router_png);
    lv_obj_set_width(ui_ImageRouter1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageRouter1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageRouter1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRouter1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRouter1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Sound1 = lv_obj_create(ui_IOT_S4);
    lv_obj_set_width(ui_Panel_Sound1, 48);
    lv_obj_set_height(ui_Panel_Sound1, 48);
    lv_obj_set_x(ui_Panel_Sound1, 104);
    lv_obj_set_y(ui_Panel_Sound1, -78);
    lv_obj_set_align(ui_Panel_Sound1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Sound1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSOund1 = lv_img_create(ui_Panel_Sound1);
    lv_img_set_src(ui_ImageSOund1, &ui_img_sound_png);
    lv_obj_set_width(ui_ImageSOund1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSOund1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageSOund1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSOund1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSOund1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelLamp1 = lv_obj_create(ui_IOT_S4);
    lv_obj_set_width(ui_PanelLamp1, 48);
    lv_obj_set_height(ui_PanelLamp1, 48);
    lv_obj_set_x(ui_PanelLamp1, -90);
    lv_obj_set_y(ui_PanelLamp1, 50);
    lv_obj_set_align(ui_PanelLamp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLamp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLamp1 = lv_img_create(ui_PanelLamp1);
    lv_img_set_src(ui_ImageLamp1, &ui_img_lamp_png);
    lv_obj_set_width(ui_ImageLamp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLamp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageLamp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLamp1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLamp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Camera1 = lv_obj_create(ui_IOT_S4);
    lv_obj_set_width(ui_Panel_Camera1, 48);
    lv_obj_set_height(ui_Panel_Camera1, 48);
    lv_obj_set_x(ui_Panel_Camera1, 10);
    lv_obj_set_y(ui_Panel_Camera1, 50);
    lv_obj_set_align(ui_Panel_Camera1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Camera1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCamera1 = lv_img_create(ui_Panel_Camera1);
    lv_img_set_src(ui_ImageCamera1, &ui_img_cameramonitor_png);
    lv_obj_set_width(ui_ImageCamera1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCamera1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageCamera1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCamera1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCamera1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Socket1 = lv_obj_create(ui_IOT_S4);
    lv_obj_set_width(ui_Panel_Socket1, 48);
    lv_obj_set_height(ui_Panel_Socket1, 48);
    lv_obj_set_x(ui_Panel_Socket1, 104);
    lv_obj_set_y(ui_Panel_Socket1, 50);
    lv_obj_set_align(ui_Panel_Socket1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Socket1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSocket1 = lv_img_create(ui_Panel_Socket1);
    lv_img_set_src(ui_ImageSocket1, &ui_img_socket_png);
    lv_obj_set_width(ui_ImageSocket1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSocket1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageSocket1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSocket1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSocket1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Home1 = lv_obj_create(ui_IOT_S4);
    lv_obj_set_width(ui_Panel_Home1, 48);
    lv_obj_set_height(ui_Panel_Home1, 50);
    lv_obj_set_x(ui_Panel_Home1, 120);
    lv_obj_set_y(ui_Panel_Home1, -210);
    lv_obj_set_align(ui_Panel_Home1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Home1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHome1 = lv_img_create(ui_Panel_Home1);
    lv_img_set_src(ui_ImageHome1, &ui_img_homepage_png);
    lv_obj_set_width(ui_ImageHome1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHome1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHome1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHome1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHome1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Panel_Return1, ui_event_Panel_Return1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Home1, ui_event_Panel_Home1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IOT_S4, ui_event_IOT_S4, LV_EVENT_ALL, NULL);

}
