// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "../ui.h"

void ui_IOT_S10_screen_init(void)
{
    ui_IOT_S10 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IOT_S10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IOT_S10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IOT_S10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S2_Bg_15 = lv_img_create(ui_IOT_S10);
    lv_img_set_src(ui_IMG_S2_Bg_15, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_15, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_15, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_15, -114);
    lv_obj_set_y(ui_IMG_S2_Bg_15, -308);
    lv_obj_set_align(ui_IMG_S2_Bg_15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_S2_Bg_16 = lv_img_create(ui_IOT_S10);
    lv_img_set_src(ui_IMG_S2_Bg_16, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_16, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_16, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_16, 145);
    lv_obj_set_y(ui_IMG_S2_Bg_16, 214);
    lv_obj_set_align(ui_IMG_S2_Bg_16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label__Connect3 = lv_label_create(ui_IOT_S10);
    lv_obj_set_width(ui_Label__Connect3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Connect3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label__Connect3, 0);
    lv_obj_set_y(ui_Label__Connect3, 15);
    lv_obj_set_align(ui_Label__Connect3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label__Connect3, "Select Device\nto connect");
    lv_obj_set_style_text_color(ui_Label__Connect3, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label__Connect3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label__Connect3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label__Connect3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Ony_MQTT3 = lv_label_create(ui_IOT_S10);
    lv_obj_set_width(ui_Label_Ony_MQTT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Ony_MQTT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Ony_MQTT3, 0);
    lv_obj_set_y(ui_Label_Ony_MQTT3, 70);
    lv_obj_set_align(ui_Label_Ony_MQTT3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Ony_MQTT3, "Only Local DataBase is possible");
    lv_obj_set_style_text_color(ui_Label_Ony_MQTT3, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Ony_MQTT3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Ony_MQTT3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Ony_MQTT3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_MQTT3 = lv_obj_create(ui_IOT_S10);
    lv_obj_set_height(ui_Panel_List_MQTT3, 84);
    lv_obj_set_width(ui_Panel_List_MQTT3, lv_pct(100));
    lv_obj_set_x(ui_Panel_List_MQTT3, 0);
    lv_obj_set_y(ui_Panel_List_MQTT3, 70);
    lv_obj_set_align(ui_Panel_List_MQTT3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel_List_MQTT3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_List_MQTT3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_MQTT3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_MQTT3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_MQTT3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_MQTT3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_MQTT4 = lv_label_create(ui_Panel_List_MQTT3);
    lv_obj_set_width(ui_Label_MQTT4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_MQTT4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_MQTT4, 110);
    lv_obj_set_y(ui_Label_MQTT4, 6);
    lv_obj_set_align(ui_Label_MQTT4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_MQTT4, "Local SQLite");
    lv_obj_set_style_text_color(ui_Label_MQTT4, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_MQTT4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_MQTT4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_MQTT4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_MQTT3 = lv_img_create(ui_Panel_List_MQTT3);
    lv_img_set_src(ui_IMG_MQTT3, &ui_img_database_png);
    lv_obj_set_width(ui_IMG_MQTT3, 48);
    lv_obj_set_height(ui_IMG_MQTT3, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_IMG_MQTT3, 45);
    lv_obj_set_y(ui_IMG_MQTT3, 6);
    lv_obj_set_align(ui_IMG_MQTT3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IMG_MQTT3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_MQTT3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Panel_List_MQTT3);
    lv_img_set_src(ui_Image1, &ui_img_circlefillgreen_png);
    lv_obj_set_width(ui_Image1, 20);
    lv_obj_set_height(ui_Image1, 20);
    lv_obj_set_x(ui_Image1, -130);
    lv_obj_set_y(ui_Image1, 6);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Return6 = lv_obj_create(ui_IOT_S10);
    lv_obj_set_width(ui_Panel_Return6, 48);
    lv_obj_set_height(ui_Panel_Return6, 48);
    lv_obj_set_x(ui_Panel_Return6, -130);
    lv_obj_set_y(ui_Panel_Return6, -210);
    lv_obj_set_align(ui_Panel_Return6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Return6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Return6 = lv_img_create(ui_Panel_Return6);
    lv_img_set_src(ui_Image_Return6, &ui_img_return_png);
    lv_obj_set_width(ui_Image_Return6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Return6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_Return6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Return6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Return6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Home6 = lv_obj_create(ui_IOT_S10);
    lv_obj_set_width(ui_Panel_Home6, 48);
    lv_obj_set_height(ui_Panel_Home6, 50);
    lv_obj_set_x(ui_Panel_Home6, 120);
    lv_obj_set_y(ui_Panel_Home6, -210);
    lv_obj_set_align(ui_Panel_Home6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Home6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHome6 = lv_img_create(ui_Panel_Home6);
    lv_img_set_src(ui_ImageHome6, &ui_img_homepage_png);
    lv_obj_set_width(ui_ImageHome6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHome6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHome6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHome6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHome6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown2 = lv_dropdown_create(ui_IOT_S10);
    lv_dropdown_set_options(ui_Dropdown2, "Device 1\nDevice 2\nDevice 3");
    lv_obj_set_width(ui_Dropdown2, 250);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 0);
    lv_obj_set_y(ui_Dropdown2, -60);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_BtnConnect1 = lv_btn_create(ui_IOT_S10);
    lv_obj_set_width(ui_BtnConnect1, 100);
    lv_obj_set_height(ui_BtnConnect1, 50);
    lv_obj_set_x(ui_BtnConnect1, 0);
    lv_obj_set_y(ui_BtnConnect1, 150);
    lv_obj_set_align(ui_BtnConnect1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnConnect1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnConnect1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnConnect1, lv_color_hex(0xEE8E23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnConnect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_BtnConnect1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Connect");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_IOT_S10, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 50);
    lv_obj_set_height(ui_Spinner2, 50);
    lv_obj_set_x(ui_Spinner2, 0);
    lv_obj_set_y(ui_Spinner2, 80);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Panel_Return6, ui_event_Panel_Return6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Home6, ui_event_Panel_Home6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnConnect1, ui_event_BtnConnect1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Spinner2, ui_event_Spinner2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IOT_S10, ui_event_IOT_S10, LV_EVENT_ALL, NULL);

}
