// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "../ui.h"

void ui_IOT_S8_screen_init(void)
{
    ui_IOT_S8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IOT_S8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IOT_S8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IOT_S8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S2_Bg_11 = lv_img_create(ui_IOT_S8);
    lv_img_set_src(ui_IMG_S2_Bg_11, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_11, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_11, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_11, -114);
    lv_obj_set_y(ui_IMG_S2_Bg_11, -308);
    lv_obj_set_align(ui_IMG_S2_Bg_11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_S2_Bg_12 = lv_img_create(ui_IOT_S8);
    lv_img_set_src(ui_IMG_S2_Bg_12, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_12, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_12, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_12, 145);
    lv_obj_set_y(ui_IMG_S2_Bg_12, 214);
    lv_obj_set_align(ui_IMG_S2_Bg_12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label__Connect1 = lv_label_create(ui_IOT_S8);
    lv_obj_set_width(ui_Label__Connect1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Connect1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label__Connect1, 0);
    lv_obj_set_y(ui_Label__Connect1, 15);
    lv_obj_set_align(ui_Label__Connect1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label__Connect1, "Select Connect\nMethod");
    lv_obj_set_style_text_color(ui_Label__Connect1, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label__Connect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label__Connect1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label__Connect1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Ony_MQTT1 = lv_label_create(ui_IOT_S8);
    lv_obj_set_width(ui_Label_Ony_MQTT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Ony_MQTT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Ony_MQTT1, 0);
    lv_obj_set_y(ui_Label_Ony_MQTT1, 70);
    lv_obj_set_align(ui_Label_Ony_MQTT1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Ony_MQTT1, "Only Local DataBase is possible");
    lv_obj_set_style_text_color(ui_Label_Ony_MQTT1, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Ony_MQTT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Ony_MQTT1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Ony_MQTT1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_MQTT1 = lv_obj_create(ui_IOT_S8);
    lv_obj_set_height(ui_Panel_List_MQTT1, 84);
    lv_obj_set_width(ui_Panel_List_MQTT1, lv_pct(100));
    lv_obj_set_x(ui_Panel_List_MQTT1, 0);
    lv_obj_set_y(ui_Panel_List_MQTT1, 150);
    lv_obj_set_align(ui_Panel_List_MQTT1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel_List_MQTT1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_List_MQTT1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_MQTT1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_MQTT1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_MQTT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_MQTT1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_Bg2 = lv_obj_create(ui_Panel_List_MQTT1);
    lv_obj_set_height(ui_Panel_List_Bg2, 70);
    lv_obj_set_width(ui_Panel_List_Bg2, lv_pct(100));
    lv_obj_set_align(ui_Panel_List_Bg2, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Panel_List_Bg2, lv_color_hex(0xF1F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_Bg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_Bg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_Bg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_List_Bg2, lv_color_hex(0x9B9DA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_List_Bg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_Bg2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_List_Bg2, lv_color_hex(0xFFCEB0), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel_List_Bg2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Panel_List_Bg2, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Panel_List_Bg2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel_MQTT_table1 = lv_obj_create(ui_Panel_List_MQTT1);
    lv_obj_set_height(ui_Panel_MQTT_table1, 20);
    lv_obj_set_width(ui_Panel_MQTT_table1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Panel_MQTT_table1, 18);
    lv_obj_set_y(ui_Panel_MQTT_table1, -10);
    lv_obj_clear_flag(ui_Panel_MQTT_table1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_Panel_MQTT_table1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_MQTT_table1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_MQTT_table1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_MQTT_table1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_MQTT_table1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_MQTT_table1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_MQTT_table1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_MQTT2 = lv_label_create(ui_Panel_MQTT_table1);
    lv_obj_set_width(ui_Label_MQTT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_MQTT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_MQTT2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_MQTT2, "MQTT");
    lv_obj_set_style_text_color(ui_Label_MQTT2, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_MQTT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_MQTT2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_MQTT2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_MQTT3 = lv_label_create(ui_Panel_List_MQTT1);
    lv_obj_set_width(ui_Label_MQTT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_MQTT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_MQTT3, 78);
    lv_obj_set_y(ui_Label_MQTT3, 6);
    lv_obj_set_align(ui_Label_MQTT3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_MQTT3, "Local DataBase");
    lv_obj_set_style_text_color(ui_Label_MQTT3, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_MQTT3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_MQTT3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_MQTT3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_MQTT1 = lv_img_create(ui_Panel_List_MQTT1);
    lv_img_set_src(ui_IMG_MQTT1, &ui_img_database_png);
    lv_obj_set_width(ui_IMG_MQTT1, 48);
    lv_obj_set_height(ui_IMG_MQTT1, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_IMG_MQTT1, 20);
    lv_obj_set_y(ui_IMG_MQTT1, 6);
    lv_obj_set_align(ui_IMG_MQTT1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IMG_MQTT1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_MQTT1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_Arrow_List_3 = lv_img_create(ui_Panel_List_MQTT1);
    lv_img_set_src(ui_IMG_Arrow_List_3, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow_List_3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow_List_3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_Arrow_List_3, -10);
    lv_obj_set_y(ui_IMG_Arrow_List_3, 6);
    lv_obj_set_align(ui_IMG_Arrow_List_3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Arrow_List_3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Arrow_List_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_IMG_Arrow_List_3, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_IMG_Arrow_List_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_Http1 = lv_obj_create(ui_IOT_S8);
    lv_obj_set_height(ui_Panel_List_Http1, 84);
    lv_obj_set_width(ui_Panel_List_Http1, lv_pct(100));
    lv_obj_set_x(ui_Panel_List_Http1, 0);
    lv_obj_set_y(ui_Panel_List_Http1, 300);
    lv_obj_set_align(ui_Panel_List_Http1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel_List_Http1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_List_Http1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_Http1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_Http1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_Http1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_Http1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_Bg3 = lv_obj_create(ui_Panel_List_Http1);
    lv_obj_set_height(ui_Panel_List_Bg3, 70);
    lv_obj_set_width(ui_Panel_List_Bg3, lv_pct(100));
    lv_obj_set_align(ui_Panel_List_Bg3, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_Panel_List_Bg3, lv_color_hex(0xF1F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_Bg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_Bg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_List_Bg3, lv_color_hex(0x9B9DA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_List_Bg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_Bg3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel_List_Bg3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Http2 = lv_label_create(ui_Panel_List_Bg3);
    lv_obj_set_width(ui_Label_Http2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Http2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Http2, 78);
    lv_obj_set_y(ui_Label_Http2, 0);
    lv_obj_set_align(ui_Label_Http2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Http2, "Online DataBase");
    lv_obj_set_style_text_color(ui_Label_Http2, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Http2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Http2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Http2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Http1 = lv_img_create(ui_Panel_List_Bg3);
    lv_img_set_src(ui_IMG_Http1, &ui_img_database_png);
    lv_obj_set_width(ui_IMG_Http1, 48);
    lv_obj_set_height(ui_IMG_Http1, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_IMG_Http1, 20);
    lv_obj_set_y(ui_IMG_Http1, 6);
    lv_obj_set_align(ui_IMG_Http1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IMG_Http1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Http1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_Arrow_List_4 = lv_img_create(ui_Panel_List_Bg3);
    lv_img_set_src(ui_IMG_Arrow_List_4, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow_List_4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow_List_4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_Arrow_List_4, -10);
    lv_obj_set_y(ui_IMG_Arrow_List_4, 0);
    lv_obj_set_align(ui_IMG_Arrow_List_4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_Arrow_List_4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Arrow_List_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_IMG_Arrow_List_4, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_IMG_Arrow_List_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_http1 = lv_obj_create(ui_Panel_List_Http1);
    lv_obj_set_height(ui_Panel_http1, 20);
    lv_obj_set_width(ui_Panel_http1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Panel_http1, 18);
    lv_obj_set_y(ui_Panel_http1, -10);
    lv_obj_clear_flag(ui_Panel_http1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_Panel_http1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_http1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_http1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_http1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_http1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_http1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_http1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Http3 = lv_label_create(ui_Panel_http1);
    lv_obj_set_width(ui_Label_Http3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Http3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Http3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Http3, "MQTT");
    lv_obj_set_style_text_color(ui_Label_Http3, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Http3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Http3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Http3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Label_Http3, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Return4 = lv_obj_create(ui_IOT_S8);
    lv_obj_set_width(ui_Panel_Return4, 48);
    lv_obj_set_height(ui_Panel_Return4, 48);
    lv_obj_set_x(ui_Panel_Return4, -130);
    lv_obj_set_y(ui_Panel_Return4, -210);
    lv_obj_set_align(ui_Panel_Return4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Return4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Return4 = lv_img_create(ui_Panel_Return4);
    lv_img_set_src(ui_Image_Return4, &ui_img_return_png);
    lv_obj_set_width(ui_Image_Return4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Return4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_Return4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Return4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Return4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Home3 = lv_obj_create(ui_IOT_S8);
    lv_obj_set_width(ui_Panel_Home3, 48);
    lv_obj_set_height(ui_Panel_Home3, 50);
    lv_obj_set_x(ui_Panel_Home3, 120);
    lv_obj_set_y(ui_Panel_Home3, -210);
    lv_obj_set_align(ui_Panel_Home3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Home3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHome3 = lv_img_create(ui_Panel_Home3);
    lv_img_set_src(ui_ImageHome3, &ui_img_homepage_png);
    lv_obj_set_width(ui_ImageHome3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHome3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHome3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHome3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHome3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Panel_List_Bg2, ui_event_Panel_List_Bg2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_List_Bg3, ui_event_Panel_List_Bg3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Return4, ui_event_Panel_Return4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Home3, ui_event_Panel_Home3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IOT_S8, ui_event_IOT_S8, LV_EVENT_ALL, NULL);

}
