// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "../ui.h"

void ui_IOT_S11_screen_init(void)
{
    ui_IOT_S11 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IOT_S11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IOT_S11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IOT_S11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S5_BG1 = lv_img_create(ui_IOT_S11);
    lv_img_set_src(ui_IMG_S5_BG1, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S5_BG1, 272);
    lv_obj_set_height(ui_IMG_S5_BG1, 336);
    lv_obj_set_align(ui_IMG_S5_BG1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_S5_BG1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S5_BG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_IMG_S5_BG1, 136, 168);

    ui_IMG_Ok_3 = lv_img_create(ui_IOT_S11);
    lv_img_set_src(ui_IMG_Ok_3, &ui_img_ok_png);
    lv_obj_set_width(ui_IMG_Ok_3, LV_SIZE_CONTENT);   /// 124
    lv_obj_set_height(ui_IMG_Ok_3, LV_SIZE_CONTENT);    /// 165
    lv_obj_set_x(ui_IMG_Ok_3, 0);
    lv_obj_set_y(ui_IMG_Ok_3, 80);
    lv_obj_set_align(ui_IMG_Ok_3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_Ok_3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Ok_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_IMG_Ok_3, 62, 62);
    lv_obj_set_style_opa(ui_IMG_Ok_3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Ok_4 = lv_img_create(ui_IOT_S11);
    lv_img_set_src(ui_IMG_Ok_4, &ui_img_ok_png);
    lv_obj_set_width(ui_IMG_Ok_4, LV_SIZE_CONTENT);   /// 124
    lv_obj_set_height(ui_IMG_Ok_4, LV_SIZE_CONTENT);    /// 165
    lv_obj_set_x(ui_IMG_Ok_4, 0);
    lv_obj_set_y(ui_IMG_Ok_4, 80);
    lv_obj_set_align(ui_IMG_Ok_4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_Ok_4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Ok_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_IMG_Ok_4, 62, 62);

    ui_Label_Succesful1 = lv_label_create(ui_IOT_S11);
    lv_obj_set_width(ui_Label_Succesful1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Succesful1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Succesful1, 0);
    lv_obj_set_y(ui_Label_Succesful1, -150);
    lv_obj_set_align(ui_Label_Succesful1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_Succesful1, "Disconnect Device\nSuccesfully!");
    lv_obj_set_style_text_color(ui_Label_Succesful1, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Succesful1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Succesful1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Succesful1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_press_contimue1 = lv_label_create(ui_IOT_S11);
    lv_obj_set_width(ui_Label_press_contimue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_press_contimue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_press_contimue1, 0);
    lv_obj_set_y(ui_Label_press_contimue1, -110);
    lv_obj_set_align(ui_Label_press_contimue1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_press_contimue1, "Press to back home");
    lv_obj_set_style_text_color(ui_Label_press_contimue1, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_press_contimue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_press_contimue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_press_contimue1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Next_1 = lv_obj_create(ui_IOT_S11);
    lv_obj_set_width(ui_BTN_Next_1, 60);
    lv_obj_set_height(ui_BTN_Next_1, 60);
    lv_obj_set_x(ui_BTN_Next_1, 0);
    lv_obj_set_y(ui_BTN_Next_1, -20);
    lv_obj_set_align(ui_BTN_Next_1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_BTN_Next_1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Next_1, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Next_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Next_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Next_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Next_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Next_1, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTN_Next_1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTN_Next_1, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTN_Next_1, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_IMG_Arrow2 = lv_img_create(ui_BTN_Next_1);
    lv_img_set_src(ui_IMG_Arrow2, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMG_Arrow2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_Arrow2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Arrow2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BTN_Next_1, ui_event_BTN_Next_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IOT_S11, ui_event_IOT_S11, LV_EVENT_ALL, NULL);

}
