// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "../ui.h"

void ui_IOT_S7_screen_init(void)
{
    ui_IOT_S7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IOT_S7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IOT_S7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IOT_S7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S2_Bg_5 = lv_img_create(ui_IOT_S7);
    lv_img_set_src(ui_IMG_S2_Bg_5, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_5, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_5, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_5, -81);
    lv_obj_set_y(ui_IMG_S2_Bg_5, -267);
    lv_obj_set_align(ui_IMG_S2_Bg_5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_S2_Bg_6 = lv_img_create(ui_IOT_S7);
    lv_img_set_src(ui_IMG_S2_Bg_6, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_6, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_6, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_6, 158);
    lv_obj_set_y(ui_IMG_S2_Bg_6, 77);
    lv_obj_set_align(ui_IMG_S2_Bg_6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Add_Device2 = lv_label_create(ui_IOT_S7);
    lv_obj_set_width(ui_Label_Add_Device2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Add_Device2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Add_Device2, 0);
    lv_obj_set_y(ui_Label_Add_Device2, 15);
    lv_obj_set_align(ui_Label_Add_Device2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Add_Device2, "Add Device");
    lv_obj_set_style_text_color(ui_Label_Add_Device2, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Add_Device2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Add_Device2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Add_Device2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Want_to_add2 = lv_label_create(ui_IOT_S7);
    lv_obj_set_width(ui_Label_Want_to_add2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Want_to_add2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Want_to_add2, 0);
    lv_obj_set_y(ui_Label_Want_to_add2, 60);
    lv_obj_set_align(ui_Label_Want_to_add2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Want_to_add2, "Pick the device you want to add\nOnly Lamp is possible!");
    lv_obj_set_style_text_color(ui_Label_Want_to_add2, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Want_to_add2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Want_to_add2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Want_to_add2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Click_to_Add_Device2 = lv_label_create(ui_IOT_S7);
    lv_obj_set_width(ui_Label_Click_to_Add_Device2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Click_to_Add_Device2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Click_to_Add_Device2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Click_to_Add_Device2, "Is Developing");
    lv_obj_set_style_text_color(ui_Label_Click_to_Add_Device2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Click_to_Add_Device2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Click_to_Add_Device2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_Click_to_Add_Device2, lv_color_hex(0xFFDAC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_Click_to_Add_Device2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label_Click_to_Add_Device2, lv_color_hex(0xFFE6DB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Return3 = lv_obj_create(ui_IOT_S7);
    lv_obj_set_width(ui_Panel_Return3, 48);
    lv_obj_set_height(ui_Panel_Return3, 48);
    lv_obj_set_x(ui_Panel_Return3, -130);
    lv_obj_set_y(ui_Panel_Return3, -210);
    lv_obj_set_align(ui_Panel_Return3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Return3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Return3 = lv_img_create(ui_Panel_Return3);
    lv_img_set_src(ui_Image_Return3, &ui_img_return_png);
    lv_obj_set_width(ui_Image_Return3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Return3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_Return3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Return3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Return3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Home4 = lv_obj_create(ui_IOT_S7);
    lv_obj_set_width(ui_Panel_Home4, 48);
    lv_obj_set_height(ui_Panel_Home4, 50);
    lv_obj_set_x(ui_Panel_Home4, 120);
    lv_obj_set_y(ui_Panel_Home4, -210);
    lv_obj_set_align(ui_Panel_Home4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Home4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHome4 = lv_img_create(ui_Panel_Home4);
    lv_img_set_src(ui_ImageHome4, &ui_img_homepage_png);
    lv_obj_set_width(ui_ImageHome4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHome4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHome4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHome4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHome4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Panel_Return3, ui_event_Panel_Return3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Home4, ui_event_Panel_Home4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IOT_S7, ui_event_IOT_S7, LV_EVENT_ALL, NULL);

}
