// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "../ui.h"

void ui_IOT_S9_screen_init(void)
{
    ui_IOT_S9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IOT_S9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IOT_S9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IOT_S9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S2_Bg_13 = lv_img_create(ui_IOT_S9);
    lv_img_set_src(ui_IMG_S2_Bg_13, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_13, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_13, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_13, -114);
    lv_obj_set_y(ui_IMG_S2_Bg_13, -308);
    lv_obj_set_align(ui_IMG_S2_Bg_13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_S2_Bg_14 = lv_img_create(ui_IOT_S9);
    lv_img_set_src(ui_IMG_S2_Bg_14, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_14, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_14, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_14, 145);
    lv_obj_set_y(ui_IMG_S2_Bg_14, 214);
    lv_obj_set_align(ui_IMG_S2_Bg_14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label__Connect2 = lv_label_create(ui_IOT_S9);
    lv_obj_set_width(ui_Label__Connect2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label__Connect2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label__Connect2, 0);
    lv_obj_set_y(ui_Label__Connect2, 15);
    lv_obj_set_align(ui_Label__Connect2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label__Connect2, "Select Device\nto connect");
    lv_obj_set_style_text_color(ui_Label__Connect2, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label__Connect2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label__Connect2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label__Connect2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Ony_MQTT2 = lv_label_create(ui_IOT_S9);
    lv_obj_set_width(ui_Label_Ony_MQTT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Ony_MQTT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Ony_MQTT2, 0);
    lv_obj_set_y(ui_Label_Ony_MQTT2, 70);
    lv_obj_set_align(ui_Label_Ony_MQTT2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Ony_MQTT2, "Only Local DataBase is possible");
    lv_obj_set_style_text_color(ui_Label_Ony_MQTT2, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Ony_MQTT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Ony_MQTT2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Ony_MQTT2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_List_MQTT2 = lv_obj_create(ui_IOT_S9);
    lv_obj_set_height(ui_Panel_List_MQTT2, 84);
    lv_obj_set_width(ui_Panel_List_MQTT2, lv_pct(100));
    lv_obj_set_x(ui_Panel_List_MQTT2, 0);
    lv_obj_set_y(ui_Panel_List_MQTT2, 70);
    lv_obj_set_align(ui_Panel_List_MQTT2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel_List_MQTT2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_List_MQTT2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_List_MQTT2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_List_MQTT2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_List_MQTT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_List_MQTT2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_MQTT5 = lv_label_create(ui_Panel_List_MQTT2);
    lv_obj_set_width(ui_Label_MQTT5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_MQTT5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_MQTT5, 110);
    lv_obj_set_y(ui_Label_MQTT5, 6);
    lv_obj_set_align(ui_Label_MQTT5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_MQTT5, "Local SQLite");
    lv_obj_set_style_text_color(ui_Label_MQTT5, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_MQTT5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_MQTT5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_MQTT5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_MQTT2 = lv_img_create(ui_Panel_List_MQTT2);
    lv_img_set_src(ui_IMG_MQTT2, &ui_img_database_png);
    lv_obj_set_width(ui_IMG_MQTT2, 48);
    lv_obj_set_height(ui_IMG_MQTT2, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_IMG_MQTT2, 45);
    lv_obj_set_y(ui_IMG_MQTT2, 6);
    lv_obj_set_align(ui_IMG_MQTT2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_IMG_MQTT2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_MQTT2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Panel_List_MQTT2);
    lv_img_set_src(ui_Image3, &ui_img_circlefillgreen_png);
    lv_obj_set_width(ui_Image3, 20);
    lv_obj_set_height(ui_Image3, 20);
    lv_obj_set_x(ui_Image3, -130);
    lv_obj_set_y(ui_Image3, 6);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Return5 = lv_obj_create(ui_IOT_S9);
    lv_obj_set_width(ui_Panel_Return5, 48);
    lv_obj_set_height(ui_Panel_Return5, 48);
    lv_obj_set_x(ui_Panel_Return5, -130);
    lv_obj_set_y(ui_Panel_Return5, -210);
    lv_obj_set_align(ui_Panel_Return5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Return5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Return5 = lv_img_create(ui_Panel_Return5);
    lv_img_set_src(ui_Image_Return5, &ui_img_return_png);
    lv_obj_set_width(ui_Image_Return5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Return5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_Return5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Return5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Return5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Home5 = lv_obj_create(ui_IOT_S9);
    lv_obj_set_width(ui_Panel_Home5, 48);
    lv_obj_set_height(ui_Panel_Home5, 50);
    lv_obj_set_x(ui_Panel_Home5, 120);
    lv_obj_set_y(ui_Panel_Home5, -210);
    lv_obj_set_align(ui_Panel_Home5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Home5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHome5 = lv_img_create(ui_Panel_Home5);
    lv_img_set_src(ui_ImageHome5, &ui_img_homepage_png);
    lv_obj_set_width(ui_ImageHome5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHome5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHome5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHome5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHome5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_IOT_S9);
    lv_dropdown_set_options(ui_Dropdown1, "Device 1\nDevice 2\nDevice 3");
    lv_obj_set_width(ui_Dropdown1, 250);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown1, -60);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_BtnConnect = lv_btn_create(ui_IOT_S9);
    lv_obj_set_width(ui_BtnConnect, 100);
    lv_obj_set_height(ui_BtnConnect, 50);
    lv_obj_set_x(ui_BtnConnect, 0);
    lv_obj_set_y(ui_BtnConnect, 150);
    lv_obj_set_align(ui_BtnConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnConnect, lv_color_hex(0xEE8E23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_BtnConnect);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Connect");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel_Return5, ui_event_Panel_Return5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Home5, ui_event_Panel_Home5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnConnect, ui_event_BtnConnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IOT_S9, ui_event_IOT_S9, LV_EVENT_ALL, NULL);

}
