// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "../ui.h"

void ui_IOT_S3_screen_init(void)
{
    ui_IOT_S3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IOT_S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IOT_S3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IOT_S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S2_Bg_1 = lv_img_create(ui_IOT_S3);
    lv_img_set_src(ui_IMG_S2_Bg_1, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_1, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_1, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_1, -81);
    lv_obj_set_y(ui_IMG_S2_Bg_1, -267);
    lv_obj_set_align(ui_IMG_S2_Bg_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_S2_Bg_2 = lv_img_create(ui_IOT_S3);
    lv_img_set_src(ui_IMG_S2_Bg_2, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_2, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_2, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_2, 158);
    lv_obj_set_y(ui_IMG_S2_Bg_2, 77);
    lv_obj_set_align(ui_IMG_S2_Bg_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Add_Device = lv_label_create(ui_IOT_S3);
    lv_obj_set_width(ui_Label_Add_Device, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Add_Device, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Add_Device, 0);
    lv_obj_set_y(ui_Label_Add_Device, 15);
    lv_obj_set_align(ui_Label_Add_Device, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Add_Device, "Add Device");
    lv_obj_set_style_text_color(ui_Label_Add_Device, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Add_Device, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Add_Device, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Add_Device, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Want_to_add = lv_label_create(ui_IOT_S3);
    lv_obj_set_width(ui_Label_Want_to_add, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Want_to_add, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Want_to_add, 0);
    lv_obj_set_y(ui_Label_Want_to_add, 60);
    lv_obj_set_align(ui_Label_Want_to_add, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Want_to_add, "Pick the device you want to add\nOnly Lamp is possible!");
    lv_obj_set_style_text_color(ui_Label_Want_to_add, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Want_to_add, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Want_to_add, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Want_to_add, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Click_to_Add_Device = lv_label_create(ui_IOT_S3);
    lv_obj_set_width(ui_Label_Click_to_Add_Device, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Click_to_Add_Device, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Click_to_Add_Device, 0);
    lv_obj_set_y(ui_Label_Click_to_Add_Device, 180);
    lv_obj_set_align(ui_Label_Click_to_Add_Device, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Click_to_Add_Device, "Click to Add Device");
    lv_obj_set_style_text_color(ui_Label_Click_to_Add_Device, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Click_to_Add_Device, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Click_to_Add_Device, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_Click_to_Add_Device, lv_color_hex(0xFFDAC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_Click_to_Add_Device, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Label_Click_to_Add_Device, lv_color_hex(0xFFE6DB), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Nas = lv_label_create(ui_IOT_S3);
    lv_obj_set_width(ui_Label_Nas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Nas, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Nas, -90);
    lv_obj_set_y(ui_Label_Nas, -45);
    lv_obj_set_align(ui_Label_Nas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Nas, "Nas/Service");

    ui_Label_Router = lv_label_create(ui_IOT_S3);
    lv_obj_set_width(ui_Label_Router, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Router, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Router, 10);
    lv_obj_set_y(ui_Label_Router, -45);
    lv_obj_set_align(ui_Label_Router, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Router, "Router");

    ui_Label_Sound = lv_label_create(ui_IOT_S3);
    lv_obj_set_width(ui_Label_Sound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Sound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Sound, 104);
    lv_obj_set_y(ui_Label_Sound, -45);
    lv_obj_set_align(ui_Label_Sound, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Sound, "Sound");

    ui_Label_Lamp = lv_label_create(ui_IOT_S3);
    lv_obj_set_width(ui_Label_Lamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Lamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Lamp, -90);
    lv_obj_set_y(ui_Label_Lamp, 88);
    lv_obj_set_align(ui_Label_Lamp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Lamp, "Lamp");

    ui_Label_Camera = lv_label_create(ui_IOT_S3);
    lv_obj_set_width(ui_Label_Camera, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Camera, LV_SIZE_CONTENT);    /// -155
    lv_obj_set_x(ui_Label_Camera, 10);
    lv_obj_set_y(ui_Label_Camera, 88);
    lv_obj_set_align(ui_Label_Camera, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Camera, "Camera");

    ui_Label_Socket = lv_label_create(ui_IOT_S3);
    lv_obj_set_width(ui_Label_Socket, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Socket, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Socket, 104);
    lv_obj_set_y(ui_Label_Socket, 88);
    lv_obj_set_align(ui_Label_Socket, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Socket, "Socket");

    ui_Panel_Return = lv_obj_create(ui_IOT_S3);
    lv_obj_set_width(ui_Panel_Return, 48);
    lv_obj_set_height(ui_Panel_Return, 48);
    lv_obj_set_x(ui_Panel_Return, -130);
    lv_obj_set_y(ui_Panel_Return, -210);
    lv_obj_set_align(ui_Panel_Return, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Return, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Return = lv_img_create(ui_Panel_Return);
    lv_img_set_src(ui_Image_Return, &ui_img_return_png);
    lv_obj_set_width(ui_Image_Return, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Return, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_Return, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Return, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Return, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Nas = lv_obj_create(ui_IOT_S3);
    lv_obj_set_width(ui_Panel_Nas, 48);
    lv_obj_set_height(ui_Panel_Nas, 48);
    lv_obj_set_x(ui_Panel_Nas, -90);
    lv_obj_set_y(ui_Panel_Nas, -80);
    lv_obj_set_align(ui_Panel_Nas, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Nas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageNas = lv_img_create(ui_Panel_Nas);
    lv_img_set_src(ui_ImageNas, &ui_img_service_png);
    lv_obj_set_width(ui_ImageNas, 48);
    lv_obj_set_height(ui_ImageNas, 48);
    lv_obj_set_align(ui_ImageNas, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageNas, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageNas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Router = lv_obj_create(ui_IOT_S3);
    lv_obj_set_width(ui_Panel_Router, 48);
    lv_obj_set_height(ui_Panel_Router, 48);
    lv_obj_set_x(ui_Panel_Router, 10);
    lv_obj_set_y(ui_Panel_Router, -80);
    lv_obj_set_align(ui_Panel_Router, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Router, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageRouter = lv_img_create(ui_Panel_Router);
    lv_img_set_src(ui_ImageRouter, &ui_img_router_png);
    lv_obj_set_width(ui_ImageRouter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageRouter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageRouter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRouter, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRouter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Sound = lv_obj_create(ui_IOT_S3);
    lv_obj_set_width(ui_Panel_Sound, 48);
    lv_obj_set_height(ui_Panel_Sound, 48);
    lv_obj_set_x(ui_Panel_Sound, 104);
    lv_obj_set_y(ui_Panel_Sound, -78);
    lv_obj_set_align(ui_Panel_Sound, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Sound, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSOund = lv_img_create(ui_Panel_Sound);
    lv_img_set_src(ui_ImageSOund, &ui_img_sound_png);
    lv_obj_set_width(ui_ImageSOund, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSOund, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageSOund, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSOund, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSOund, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelLamp = lv_obj_create(ui_IOT_S3);
    lv_obj_set_width(ui_PanelLamp, 48);
    lv_obj_set_height(ui_PanelLamp, 48);
    lv_obj_set_x(ui_PanelLamp, -90);
    lv_obj_set_y(ui_PanelLamp, 50);
    lv_obj_set_align(ui_PanelLamp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLamp = lv_img_create(ui_PanelLamp);
    lv_img_set_src(ui_ImageLamp, &ui_img_lamp_png);
    lv_obj_set_width(ui_ImageLamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageLamp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLamp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Camera = lv_obj_create(ui_IOT_S3);
    lv_obj_set_width(ui_Panel_Camera, 48);
    lv_obj_set_height(ui_Panel_Camera, 48);
    lv_obj_set_x(ui_Panel_Camera, 10);
    lv_obj_set_y(ui_Panel_Camera, 50);
    lv_obj_set_align(ui_Panel_Camera, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Camera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCamera = lv_img_create(ui_Panel_Camera);
    lv_img_set_src(ui_ImageCamera, &ui_img_cameramonitor_png);
    lv_obj_set_width(ui_ImageCamera, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCamera, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageCamera, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCamera, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCamera, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Socket = lv_obj_create(ui_IOT_S3);
    lv_obj_set_width(ui_Panel_Socket, 48);
    lv_obj_set_height(ui_Panel_Socket, 48);
    lv_obj_set_x(ui_Panel_Socket, 104);
    lv_obj_set_y(ui_Panel_Socket, 50);
    lv_obj_set_align(ui_Panel_Socket, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Socket, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSocket = lv_img_create(ui_Panel_Socket);
    lv_img_set_src(ui_ImageSocket, &ui_img_socket_png);
    lv_obj_set_width(ui_ImageSocket, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSocket, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageSocket, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSocket, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSocket, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Home = lv_obj_create(ui_IOT_S3);
    lv_obj_set_width(ui_Panel_Home, 48);
    lv_obj_set_height(ui_Panel_Home, 50);
    lv_obj_set_x(ui_Panel_Home, 120);
    lv_obj_set_y(ui_Panel_Home, -210);
    lv_obj_set_align(ui_Panel_Home, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHome = lv_img_create(ui_Panel_Home);
    lv_img_set_src(ui_ImageHome, &ui_img_homepage_png);
    lv_obj_set_width(ui_ImageHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHome, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Panel_Return, ui_event_Panel_Return, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Nas, ui_event_Panel_Nas, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Router, ui_event_Panel_Router, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Sound, ui_event_Panel_Sound, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelLamp, ui_event_PanelLamp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Camera, ui_event_Panel_Camera, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Socket, ui_event_Panel_Socket, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Home, ui_event_Panel_Home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IOT_S3, ui_event_IOT_S3, LV_EVENT_ALL, NULL);

}
