// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "../ui.h"

void ui_IOT_S12_screen_init(void)
{
    ui_IOT_S12 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IOT_S12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IOT_S12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IOT_S12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S2_Bg_17 = lv_img_create(ui_IOT_S12);
    lv_img_set_src(ui_IMG_S2_Bg_17, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_17, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_17, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_17, -81);
    lv_obj_set_y(ui_IMG_S2_Bg_17, -267);
    lv_obj_set_align(ui_IMG_S2_Bg_17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_S2_Bg_18 = lv_img_create(ui_IOT_S12);
    lv_img_set_src(ui_IMG_S2_Bg_18, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S2_Bg_18, 272);
    lv_obj_set_height(ui_IMG_S2_Bg_18, 336);
    lv_obj_set_x(ui_IMG_S2_Bg_18, 158);
    lv_obj_set_y(ui_IMG_S2_Bg_18, 77);
    lv_obj_set_align(ui_IMG_S2_Bg_18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_S2_Bg_18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S2_Bg_18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Add_Device3 = lv_label_create(ui_IOT_S12);
    lv_obj_set_width(ui_Label_Add_Device3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Add_Device3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Add_Device3, 0);
    lv_obj_set_y(ui_Label_Add_Device3, 15);
    lv_obj_set_align(ui_Label_Add_Device3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Add_Device3, "Lamp");
    lv_obj_set_style_text_color(ui_Label_Add_Device3, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Add_Device3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Add_Device3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Add_Device3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Want_to_add3 = lv_label_create(ui_IOT_S12);
    lv_obj_set_width(ui_Label_Want_to_add3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Want_to_add3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Want_to_add3, 0);
    lv_obj_set_y(ui_Label_Want_to_add3, 60);
    lv_obj_set_align(ui_Label_Want_to_add3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Want_to_add3, "Type to Send Message");
    lv_obj_set_style_text_color(ui_Label_Want_to_add3, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Want_to_add3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Want_to_add3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Want_to_add3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Return7 = lv_obj_create(ui_IOT_S12);
    lv_obj_set_width(ui_Panel_Return7, 48);
    lv_obj_set_height(ui_Panel_Return7, 48);
    lv_obj_set_x(ui_Panel_Return7, -130);
    lv_obj_set_y(ui_Panel_Return7, -210);
    lv_obj_set_align(ui_Panel_Return7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Return7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_Return7 = lv_img_create(ui_Panel_Return7);
    lv_img_set_src(ui_Image_Return7, &ui_img_return_png);
    lv_obj_set_width(ui_Image_Return7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_Return7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_Return7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Return7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Return7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelLamp2 = lv_obj_create(ui_IOT_S12);
    lv_obj_set_width(ui_PanelLamp2, 48);
    lv_obj_set_height(ui_PanelLamp2, 48);
    lv_obj_set_x(ui_PanelLamp2, -30);
    lv_obj_set_y(ui_PanelLamp2, -100);
    lv_obj_set_align(ui_PanelLamp2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLamp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLamp2 = lv_img_create(ui_PanelLamp2);
    lv_img_set_src(ui_ImageLamp2, &ui_img_lamp_png);
    lv_obj_set_width(ui_ImageLamp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLamp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageLamp2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLamp2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLamp2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Home7 = lv_obj_create(ui_IOT_S12);
    lv_obj_set_width(ui_Panel_Home7, 48);
    lv_obj_set_height(ui_Panel_Home7, 50);
    lv_obj_set_x(ui_Panel_Home7, 120);
    lv_obj_set_y(ui_Panel_Home7, -210);
    lv_obj_set_align(ui_Panel_Home7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Home7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageHome7 = lv_img_create(ui_Panel_Home7);
    lv_img_set_src(ui_ImageHome7, &ui_img_homepage_png);
    lv_obj_set_width(ui_ImageHome7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHome7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHome7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHome7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHome7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_IOT_S12);
    lv_obj_set_width(ui_TextArea1, 300);
    lv_obj_set_height(ui_TextArea1, 70);
    lv_obj_set_x(ui_TextArea1, 10);
    lv_obj_set_y(ui_TextArea1, 200);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");



    ui_Keyboard2 = lv_keyboard_create(ui_IOT_S12);
    lv_obj_set_width(ui_Keyboard2, 300);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 4);
    lv_obj_set_y(ui_Keyboard2, 176);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_ImageLight = lv_img_create(ui_IOT_S12);
    lv_img_set_src(ui_ImageLight, &ui_img_circlefillred_png);
    lv_obj_set_width(ui_ImageLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageLight, 30);
    lv_obj_set_y(ui_ImageLight, -100);
    lv_obj_set_align(ui_ImageLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnSendMessage = lv_btn_create(ui_IOT_S12);
    lv_obj_set_width(ui_BtnSendMessage, 110);
    lv_obj_set_height(ui_BtnSendMessage, 50);
    lv_obj_set_x(ui_BtnSendMessage, 0);
    lv_obj_set_y(ui_BtnSendMessage, 70);
    lv_obj_set_align(ui_BtnSendMessage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSendMessage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSendMessage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSendMessage, lv_color_hex(0xEE8E23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSendMessage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_BtnSendMessage);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Send");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel_Return7, ui_event_Panel_Return7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelLamp2, ui_event_PanelLamp2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel_Home7, ui_event_Panel_Home7, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea1);
    lv_obj_add_event_cb(ui_BtnSendMessage, ui_event_BtnSendMessage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IOT_S12, ui_event_IOT_S12, LV_EVENT_ALL, NULL);

}
