// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void FadeOn_Animation(lv_obj_t * TargetObject, int delay);
void BGOn_Animation(lv_obj_t * TargetObject, int delay);
void FadeOnOpa_Animation(lv_obj_t * TargetObject, int delay);
void FadeOnUp_Animation(lv_obj_t * TargetObject, int delay);
void FadeOff_Animation(lv_obj_t * TargetObject, int delay);
void Keyboard_Animation(lv_obj_t * TargetObject, int delay);
void BGAnim_Animation(lv_obj_t * TargetObject, int delay);
void Ready_Animation(lv_obj_t * TargetObject, int delay);
void ReadyOpa_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_IOT_S1
void ui_IOT_S1_screen_init(void);
void ui_event_IOT_S1(lv_event_t * e);
lv_obj_t * ui_IOT_S1;
lv_obj_t * ui_IMG_S1_BG;
lv_obj_t * ui_Circle_1;
lv_obj_t * ui_Circle_2;
lv_obj_t * ui_IMG_POS;
lv_obj_t * ui_Label_Device_Manager;
lv_obj_t * ui_Label_Lets_get;
void ui_event_BTN_Next(lv_event_t * e);
lv_obj_t * ui_BTN_Next;
lv_obj_t * ui_IMG_Arrow;


// SCREEN: ui_IOT_S3
void ui_IOT_S3_screen_init(void);
void ui_event_IOT_S3(lv_event_t * e);
lv_obj_t * ui_IOT_S3;
lv_obj_t * ui_IMG_S2_Bg_1;
lv_obj_t * ui_IMG_S2_Bg_2;
lv_obj_t * ui_Label_Add_Device;
lv_obj_t * ui_Label_Want_to_add;
lv_obj_t * ui_Label_Click_to_Add_Device;
lv_obj_t * ui_Label_Nas;
lv_obj_t * ui_Label_Router;
lv_obj_t * ui_Label_Sound;
lv_obj_t * ui_Label_Lamp;
lv_obj_t * ui_Label_Camera;
lv_obj_t * ui_Label_Socket;
void ui_event_Panel_Return(lv_event_t * e);
lv_obj_t * ui_Panel_Return;
lv_obj_t * ui_Image_Return;
lv_obj_t * ui_Panel_Nas;
lv_obj_t * ui_ImageNas;
lv_obj_t * ui_Panel_Router;
lv_obj_t * ui_ImageRouter;
lv_obj_t * ui_Panel_Sound;
lv_obj_t * ui_ImageSOund;
void ui_event_PanelLamp(lv_event_t * e);
lv_obj_t * ui_PanelLamp;
lv_obj_t * ui_ImageLamp;
lv_obj_t * ui_Panel_Camera;
lv_obj_t * ui_ImageCamera;
lv_obj_t * ui_Panel_Socket;
lv_obj_t * ui_ImageSocket;
void ui_event_Panel_Home(lv_event_t * e);
lv_obj_t * ui_Panel_Home;
lv_obj_t * ui_ImageHome;


// SCREEN: ui_IOT_S5
void ui_IOT_S5_screen_init(void);
void ui_event_IOT_S5(lv_event_t * e);
lv_obj_t * ui_IOT_S5;
lv_obj_t * ui_IMG_S2_Bg_3;
lv_obj_t * ui_IMG_S2_Bg_4;
lv_obj_t * ui_Label__Connect;
lv_obj_t * ui_Label_Ony_MQTT;
lv_obj_t * ui_Panel_List_MQTT;
void ui_event_Panel_List_Bg(lv_event_t * e);
lv_obj_t * ui_Panel_List_Bg;
lv_obj_t * ui_Panel_MQTT_table;
lv_obj_t * ui_Label_MQTT1;
lv_obj_t * ui_Label_MQTT;
lv_obj_t * ui_IMG_MQTT;
lv_obj_t * ui_IMG_Arrow_List_1;
lv_obj_t * ui_Panel_List_Http;
lv_obj_t * ui_Panel_List_Bg1;
lv_obj_t * ui_Label_Http;
lv_obj_t * ui_IMG_Http;
lv_obj_t * ui_IMG_Arrow_List_2;
lv_obj_t * ui_Panel_http;
lv_obj_t * ui_Label_Http1;
void ui_event_Panel_Return2(lv_event_t * e);
lv_obj_t * ui_Panel_Return2;
lv_obj_t * ui_Image_Return2;
void ui_event_Panel_Home2(lv_event_t * e);
lv_obj_t * ui_Panel_Home2;
lv_obj_t * ui_ImageHome2;


// SCREEN: ui_IOT_S6
void ui_IOT_S6_screen_init(void);
void ui_event_IOT_S6(lv_event_t * e);
lv_obj_t * ui_IOT_S6;
lv_obj_t * ui_IMG_S5_BG;
lv_obj_t * ui_IMG_Ok_1;
lv_obj_t * ui_IMG_Ok_2;
lv_obj_t * ui_Label_Succesful;
lv_obj_t * ui_Label_press_contimue;
void ui_event_BTN_Next_2(lv_event_t * e);
lv_obj_t * ui_BTN_Next_2;
lv_obj_t * ui_IMG_Arrow1;


// SCREEN: ui_IOT_S2
void ui_IOT_S2_screen_init(void);
void ui_event_IOT_S2(lv_event_t * e);
lv_obj_t * ui_IOT_S2;
lv_obj_t * ui_IMG_S2_Bg_7;
lv_obj_t * ui_IMG_S2_Bg_8;
lv_obj_t * ui_Label_Enter_Amount1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_Label7;
lv_obj_t * ui_TabPage4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_TabPage5;
lv_obj_t * ui_Label9;
lv_obj_t * ui_TabPage6;
lv_obj_t * ui_Label10;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label11;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label4;


// SCREEN: ui_IOT_S4
void ui_IOT_S4_screen_init(void);
void ui_event_IOT_S4(lv_event_t * e);
lv_obj_t * ui_IOT_S4;
lv_obj_t * ui_IMG_S2_Bg_9;
lv_obj_t * ui_IMG_S2_Bg_10;
lv_obj_t * ui_Label_Add_Device1;
lv_obj_t * ui_Label_Want_to_add1;
lv_obj_t * ui_Label_Click_to_Add_Device1;
lv_obj_t * ui_Label_Nas1;
lv_obj_t * ui_Label_Router1;
lv_obj_t * ui_Label_Sound1;
lv_obj_t * ui_Label_Lamp1;
lv_obj_t * ui_Label_Camera1;
lv_obj_t * ui_Label_Socket1;
void ui_event_Panel_Return1(lv_event_t * e);
lv_obj_t * ui_Panel_Return1;
lv_obj_t * ui_Image_Return1;
lv_obj_t * ui_Panel_Nas1;
lv_obj_t * ui_ImageNas1;
lv_obj_t * ui_Panel_Router1;
lv_obj_t * ui_ImageRouter1;
lv_obj_t * ui_Panel_Sound1;
lv_obj_t * ui_ImageSOund1;
lv_obj_t * ui_PanelLamp1;
lv_obj_t * ui_ImageLamp1;
lv_obj_t * ui_Panel_Camera1;
lv_obj_t * ui_ImageCamera1;
lv_obj_t * ui_Panel_Socket1;
lv_obj_t * ui_ImageSocket1;
void ui_event_Panel_Home1(lv_event_t * e);
lv_obj_t * ui_Panel_Home1;
lv_obj_t * ui_ImageHome1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_img_bg_[1] = {&ui_img_img_bg_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void FadeOn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 300);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, -20, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_1);

}
void BGOn_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void FadeOnOpa_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 30);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 300);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, -30, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_1);

}
void FadeOnUp_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 20, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 300);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void FadeOff_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void Keyboard_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 300);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_height);
    lv_anim_set_values(&PropertyAnimation_1, 150, 220);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}
void BGAnim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 4000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_1, 300, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_1);

}
void Ready_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 400);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_1, -450, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}
void ReadyOpa_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 150);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 300);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 150, 0);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 300);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 1000);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_2, 255, 500);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_start(&PropertyAnimation_2);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_IOT_S1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        BGAnim_Animation(ui_IMG_S1_BG, 0);
        FadeOnOpa_Animation(ui_Circle_2, 50);
        FadeOnUp_Animation(ui_Circle_1, 200);
        FadeOn_Animation(ui_IMG_POS, 350);
        FadeOnUp_Animation(ui_Label_Device_Manager, 0);
        FadeOnUp_Animation(ui_Label_Lets_get, 150);
        FadeOnUp_Animation(ui_BTN_Next, 300);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        FadeOff_Animation(ui_IMG_S1_BG, 0);
        FadeOff_Animation(ui_Circle_1, 50);
        FadeOff_Animation(ui_Label_Lets_get, 250);
        _ui_opacity_set(ui_Circle_2, 0);
        FadeOff_Animation(ui_BTN_Next, 300);
        FadeOff_Animation(ui_Label_Device_Manager, 250);
    }
}
void ui_event_BTN_Next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S2_screen_init);
    }
}
void ui_event_IOT_S3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        FadeOnUp_Animation(ui_Panel_Router, 200);
        FadeOnUp_Animation(ui_Panel_Home, 200);
        FadeOnUp_Animation(ui_Panel_Socket, 200);
        FadeOnUp_Animation(ui_Panel_Camera, 200);
        FadeOnUp_Animation(ui_Label_Add_Device, 200);
        FadeOnUp_Animation(ui_Panel_Sound, 200);
        FadeOn_Animation(ui_IMG_S2_Bg_1, 50);
        FadeOn_Animation(ui_Label_Want_to_add, 50);
        FadeOn_Animation(ui_Label_Click_to_Add_Device, 50);
        FadeOnUp_Animation(ui_Panel_Nas, 200);
        FadeOnUp_Animation(ui_Label_Socket, 200);
        FadeOnUp_Animation(ui_Label_Camera, 200);
        FadeOnUp_Animation(ui_Label_Lamp, 200);
        FadeOnUp_Animation(ui_Label_Sound, 200);
        FadeOnUp_Animation(ui_Label_Router, 200);
        FadeOnUp_Animation(ui_Label_Nas, 200);
        FadeOnUp_Animation(ui_Panel_Return, 200);
        FadeOnUp_Animation(ui_PanelLamp, 200);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        FadeOff_Animation(ui_IMG_S2_Bg_1, 0);
        FadeOff_Animation(ui_IMG_S2_Bg_2, 100);
        FadeOff_Animation(ui_IOT_S3, 500);
        FadeOff_Animation(ui_Label_Click_to_Add_Device, 150);
        FadeOff_Animation(ui_Label_Want_to_add, 200);
        FadeOff_Animation(ui_Label_Add_Device, 250);
    }
}
void ui_event_Panel_Return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S2_screen_init);
    }
}
void ui_event_PanelLamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S5, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S5_screen_init);
    }
}
void ui_event_Panel_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S2_screen_init);
    }
}
void ui_event_IOT_S5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        BGOn_Animation(ui_IMG_S2_Bg_3, 0);
        BGOn_Animation(ui_IMG_S2_Bg_4, 200);
        FadeOn_Animation(ui_Label__Connect, 0);
        FadeOn_Animation(ui_Label_Ony_MQTT, 100);
        FadeOnUp_Animation(ui_Panel_List_Http, 200);
        FadeOnUp_Animation(ui_Panel_List_MQTT, 300);
        FadeOnUp_Animation(ui_Panel_Return2, 200);
        FadeOnUp_Animation(ui_Panel_Home2, 200);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        FadeOff_Animation(ui_IMG_S2_Bg_3, 0);
        FadeOff_Animation(ui_IMG_S2_Bg_4, 100);
        FadeOff_Animation(ui_Label__Connect, 0);
        FadeOff_Animation(ui_Label_Ony_MQTT, 50);
        FadeOff_Animation(ui_Panel_List_MQTT, 100);
        FadeOff_Animation(ui_Panel_List_Http, 150);
        FadeOff_Animation(ui_Panel_Home2, 200);
        FadeOff_Animation(ui_Panel_Return2, 250);
    }
}
void ui_event_Panel_List_Bg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S6, LV_SCR_LOAD_ANIM_FADE_ON, 50, 400, &ui_IOT_S6_screen_init);
    }
}
void ui_event_Panel_Return2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S3_screen_init);
    }
}
void ui_event_Panel_Home2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S2_screen_init);
    }
}
void ui_event_IOT_S6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        BGAnim_Animation(ui_IMG_S5_BG, 0);
        Ready_Animation(ui_IMG_Ok_2, 200);
        ReadyOpa_Animation(ui_IMG_Ok_1, 300);
        FadeOnUp_Animation(ui_BTN_Next_2, 0);
        FadeOnUp_Animation(ui_Label_press_contimue, 100);
        FadeOnUp_Animation(ui_Label_Succesful, 200);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        FadeOff_Animation(ui_IMG_S5_BG, 0);
        FadeOff_Animation(ui_IMG_Ok_2, 50);
        FadeOff_Animation(ui_Label_Succesful, 100);
        FadeOff_Animation(ui_Label_press_contimue, 150);
        FadeOff_Animation(ui_BTN_Next_2, 200);
    }
}
void ui_event_BTN_Next_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S2, LV_SCR_LOAD_ANIM_FADE_ON, 50, 400, &ui_IOT_S2_screen_init);
    }
}
void ui_event_IOT_S2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        BGOn_Animation(ui_IMG_S2_Bg_7, 0);
        BGOn_Animation(ui_IMG_S2_Bg_8, 100);
        FadeOn_Animation(ui_Button2, 200);
        FadeOn_Animation(ui_Button5, 200);
        FadeOnUp_Animation(ui_Label_Enter_Amount1, 200);
        FadeOnUp_Animation(ui_TabView1, 200);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        FadeOff_Animation(ui_IMG_S2_Bg_7, 0);
        FadeOff_Animation(ui_IMG_S2_Bg_8, 0);
        FadeOff_Animation(ui_IOT_S2, 500);
        FadeOff_Animation(ui_Button5, 150);
        FadeOff_Animation(ui_Button2, 150);
        FadeOff_Animation(ui_Label_Enter_Amount1, 250);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S3_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S4, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S4_screen_init);
    }
}
void ui_event_IOT_S4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        FadeOnUp_Animation(ui_Panel_Router1, 200);
        FadeOnUp_Animation(ui_Panel_Home1, 200);
        FadeOnUp_Animation(ui_Panel_Socket1, 200);
        FadeOnUp_Animation(ui_Panel_Camera1, 200);
        FadeOnUp_Animation(ui_Label_Add_Device1, 200);
        FadeOnUp_Animation(ui_Panel_Sound1, 200);
        FadeOn_Animation(ui_IMG_S2_Bg_9, 50);
        FadeOn_Animation(ui_Label_Want_to_add1, 50);
        FadeOn_Animation(ui_Label_Click_to_Add_Device1, 50);
        FadeOnUp_Animation(ui_Panel_Nas1, 200);
        FadeOnUp_Animation(ui_Label_Socket1, 200);
        FadeOnUp_Animation(ui_Label_Camera1, 200);
        FadeOnUp_Animation(ui_Label_Lamp1, 200);
        FadeOnUp_Animation(ui_Label_Sound1, 200);
        FadeOnUp_Animation(ui_Label_Router1, 200);
        FadeOnUp_Animation(ui_Label_Nas1, 200);
        FadeOnUp_Animation(ui_Panel_Return1, 200);
        FadeOnUp_Animation(ui_PanelLamp1, 200);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        FadeOff_Animation(ui_IMG_S2_Bg_9, 0);
        FadeOff_Animation(ui_IMG_S2_Bg_10, 100);
        FadeOff_Animation(ui_IOT_S4, 500);
        FadeOff_Animation(ui_Label_Click_to_Add_Device1, 150);
        FadeOff_Animation(ui_Label_Want_to_add1, 200);
        FadeOff_Animation(ui_Label_Add_Device1, 250);
    }
}
void ui_event_Panel_Return1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S2_screen_init);
    }
}
void ui_event_Panel_Home1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_IOT_S2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_IOT_S2_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_IOT_S1_screen_init();
    ui_IOT_S3_screen_init();
    ui_IOT_S5_screen_init();
    ui_IOT_S6_screen_init();
    ui_IOT_S2_screen_init();
    ui_IOT_S4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_IOT_S1);
}
