// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#ifndef _POS_UI_H
#define _POS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void FadeOn_Animation(lv_obj_t * TargetObject, int delay);
void BGOn_Animation(lv_obj_t * TargetObject, int delay);
void FadeOnOpa_Animation(lv_obj_t * TargetObject, int delay);
void FadeOnUp_Animation(lv_obj_t * TargetObject, int delay);
void FadeOff_Animation(lv_obj_t * TargetObject, int delay);
void Keyboard_Animation(lv_obj_t * TargetObject, int delay);
void BGAnim_Animation(lv_obj_t * TargetObject, int delay);
void Ready_Animation(lv_obj_t * TargetObject, int delay);
void ReadyOpa_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_IOT_S1
void ui_IOT_S1_screen_init(void);
void ui_event_IOT_S1(lv_event_t * e);
extern lv_obj_t * ui_IOT_S1;
extern lv_obj_t * ui_IMG_S1_BG;
extern lv_obj_t * ui_Circle_1;
extern lv_obj_t * ui_Circle_2;
extern lv_obj_t * ui_IMG_POS;
extern lv_obj_t * ui_Label_Device_Manager;
extern lv_obj_t * ui_Label_Lets_get;
void ui_event_BTN_Next(lv_event_t * e);
extern lv_obj_t * ui_BTN_Next;
extern lv_obj_t * ui_IMG_Arrow;
// SCREEN: ui_IOT_S3
void ui_IOT_S3_screen_init(void);
void ui_event_IOT_S3(lv_event_t * e);
extern lv_obj_t * ui_IOT_S3;
extern lv_obj_t * ui_IMG_S2_Bg_1;
extern lv_obj_t * ui_IMG_S2_Bg_2;
extern lv_obj_t * ui_Label_Add_Device;
extern lv_obj_t * ui_Label_Want_to_add;
extern lv_obj_t * ui_Label_Click_to_Add_Device;
extern lv_obj_t * ui_Label_Nas;
extern lv_obj_t * ui_Label_Router;
extern lv_obj_t * ui_Label_Sound;
extern lv_obj_t * ui_Label_Lamp;
extern lv_obj_t * ui_Label_Camera;
extern lv_obj_t * ui_Label_Socket;
void ui_event_Panel_Return(lv_event_t * e);
extern lv_obj_t * ui_Panel_Return;
extern lv_obj_t * ui_Image_Return;
void ui_event_Panel_Nas(lv_event_t * e);
extern lv_obj_t * ui_Panel_Nas;
extern lv_obj_t * ui_ImageNas;
void ui_event_Panel_Router(lv_event_t * e);
extern lv_obj_t * ui_Panel_Router;
extern lv_obj_t * ui_ImageRouter;
void ui_event_Panel_Sound(lv_event_t * e);
extern lv_obj_t * ui_Panel_Sound;
extern lv_obj_t * ui_ImageSOund;
void ui_event_PanelLamp(lv_event_t * e);
extern lv_obj_t * ui_PanelLamp;
extern lv_obj_t * ui_ImageLamp;
void ui_event_Panel_Camera(lv_event_t * e);
extern lv_obj_t * ui_Panel_Camera;
extern lv_obj_t * ui_ImageCamera;
void ui_event_Panel_Socket(lv_event_t * e);
extern lv_obj_t * ui_Panel_Socket;
extern lv_obj_t * ui_ImageSocket;
void ui_event_Panel_Home(lv_event_t * e);
extern lv_obj_t * ui_Panel_Home;
extern lv_obj_t * ui_ImageHome;
// SCREEN: ui_IOT_S5
void ui_IOT_S5_screen_init(void);
void ui_event_IOT_S5(lv_event_t * e);
extern lv_obj_t * ui_IOT_S5;
extern lv_obj_t * ui_IMG_S2_Bg_3;
extern lv_obj_t * ui_IMG_S2_Bg_4;
extern lv_obj_t * ui_Label__Connect;
extern lv_obj_t * ui_Label_Ony_MQTT;
extern lv_obj_t * ui_Panel_List_MQTT;
void ui_event_Panel_List_Bg(lv_event_t * e);
extern lv_obj_t * ui_Panel_List_Bg;
extern lv_obj_t * ui_Panel_MQTT_table;
extern lv_obj_t * ui_Label_MQTT1;
extern lv_obj_t * ui_Label_MQTT;
extern lv_obj_t * ui_IMG_MQTT;
extern lv_obj_t * ui_IMG_Arrow_List_1;
extern lv_obj_t * ui_Panel_List_Http;
void ui_event_Panel_List_Bg1(lv_event_t * e);
extern lv_obj_t * ui_Panel_List_Bg1;
extern lv_obj_t * ui_Label_Http;
extern lv_obj_t * ui_IMG_Http;
extern lv_obj_t * ui_IMG_Arrow_List_2;
extern lv_obj_t * ui_Panel_http;
extern lv_obj_t * ui_Label_Http1;
void ui_event_Panel_Return2(lv_event_t * e);
extern lv_obj_t * ui_Panel_Return2;
extern lv_obj_t * ui_Image_Return2;
void ui_event_Panel_Home2(lv_event_t * e);
extern lv_obj_t * ui_Panel_Home2;
extern lv_obj_t * ui_ImageHome2;
// SCREEN: ui_IOT_S6
void ui_IOT_S6_screen_init(void);
void ui_event_IOT_S6(lv_event_t * e);
extern lv_obj_t * ui_IOT_S6;
extern lv_obj_t * ui_IMG_S5_BG;
extern lv_obj_t * ui_IMG_Ok_1;
extern lv_obj_t * ui_IMG_Ok_2;
extern lv_obj_t * ui_Label_Succesful;
extern lv_obj_t * ui_Label_press_contimue;
void ui_event_BTN_Next_2(lv_event_t * e);
extern lv_obj_t * ui_BTN_Next_2;
extern lv_obj_t * ui_IMG_Arrow1;
// SCREEN: ui_IOT_S2
void ui_IOT_S2_screen_init(void);
void ui_event_IOT_S2(lv_event_t * e);
extern lv_obj_t * ui_IOT_S2;
extern lv_obj_t * ui_IMG_S2_Bg_7;
extern lv_obj_t * ui_IMG_S2_Bg_8;
extern lv_obj_t * ui_Label_Enter_Amount1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_TabPage5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_TabPage6;
extern lv_obj_t * ui_Label10;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_IOT_S4
void ui_IOT_S4_screen_init(void);
void ui_event_IOT_S4(lv_event_t * e);
extern lv_obj_t * ui_IOT_S4;
extern lv_obj_t * ui_IMG_S2_Bg_9;
extern lv_obj_t * ui_IMG_S2_Bg_10;
extern lv_obj_t * ui_Label_Add_Device1;
extern lv_obj_t * ui_Label_Want_to_add1;
extern lv_obj_t * ui_Label_Click_to_Add_Device1;
extern lv_obj_t * ui_Label_Nas1;
extern lv_obj_t * ui_Label_Router1;
extern lv_obj_t * ui_Label_Sound1;
extern lv_obj_t * ui_Label_Lamp1;
extern lv_obj_t * ui_Label_Camera1;
extern lv_obj_t * ui_Label_Socket1;
void ui_event_Panel_Return1(lv_event_t * e);
extern lv_obj_t * ui_Panel_Return1;
extern lv_obj_t * ui_Image_Return1;
extern lv_obj_t * ui_Panel_Nas1;
extern lv_obj_t * ui_ImageNas1;
extern lv_obj_t * ui_Panel_Router1;
extern lv_obj_t * ui_ImageRouter1;
extern lv_obj_t * ui_Panel_Sound1;
extern lv_obj_t * ui_ImageSOund1;
extern lv_obj_t * ui_PanelLamp1;
extern lv_obj_t * ui_ImageLamp1;
extern lv_obj_t * ui_Panel_Camera1;
extern lv_obj_t * ui_ImageCamera1;
extern lv_obj_t * ui_Panel_Socket1;
extern lv_obj_t * ui_ImageSocket1;
void ui_event_Panel_Home1(lv_event_t * e);
extern lv_obj_t * ui_Panel_Home1;
extern lv_obj_t * ui_ImageHome1;
// SCREEN: ui_IOT_S7
void ui_IOT_S7_screen_init(void);
void ui_event_IOT_S7(lv_event_t * e);
extern lv_obj_t * ui_IOT_S7;
extern lv_obj_t * ui_IMG_S2_Bg_5;
extern lv_obj_t * ui_IMG_S2_Bg_6;
extern lv_obj_t * ui_Label_Add_Device2;
extern lv_obj_t * ui_Label_Want_to_add2;
extern lv_obj_t * ui_Label_Click_to_Add_Device2;
void ui_event_Panel_Return3(lv_event_t * e);
extern lv_obj_t * ui_Panel_Return3;
extern lv_obj_t * ui_Image_Return3;
void ui_event_Panel_Home4(lv_event_t * e);
extern lv_obj_t * ui_Panel_Home4;
extern lv_obj_t * ui_ImageHome4;
// SCREEN: ui_IOT_S8
void ui_IOT_S8_screen_init(void);
void ui_event_IOT_S8(lv_event_t * e);
extern lv_obj_t * ui_IOT_S8;
extern lv_obj_t * ui_IMG_S2_Bg_11;
extern lv_obj_t * ui_IMG_S2_Bg_12;
extern lv_obj_t * ui_Label__Connect1;
extern lv_obj_t * ui_Label_Ony_MQTT1;
extern lv_obj_t * ui_Panel_List_MQTT1;
void ui_event_Panel_List_Bg2(lv_event_t * e);
extern lv_obj_t * ui_Panel_List_Bg2;
extern lv_obj_t * ui_Panel_MQTT_table1;
extern lv_obj_t * ui_Label_MQTT2;
extern lv_obj_t * ui_Label_MQTT3;
extern lv_obj_t * ui_IMG_MQTT1;
extern lv_obj_t * ui_IMG_Arrow_List_3;
extern lv_obj_t * ui_Panel_List_Http1;
void ui_event_Panel_List_Bg3(lv_event_t * e);
extern lv_obj_t * ui_Panel_List_Bg3;
extern lv_obj_t * ui_Label_Http2;
extern lv_obj_t * ui_IMG_Http1;
extern lv_obj_t * ui_IMG_Arrow_List_4;
extern lv_obj_t * ui_Panel_http1;
extern lv_obj_t * ui_Label_Http3;
void ui_event_Panel_Return4(lv_event_t * e);
extern lv_obj_t * ui_Panel_Return4;
extern lv_obj_t * ui_Image_Return4;
void ui_event_Panel_Home3(lv_event_t * e);
extern lv_obj_t * ui_Panel_Home3;
extern lv_obj_t * ui_ImageHome3;
// SCREEN: ui_IOT_S9
void ui_IOT_S9_screen_init(void);
void ui_event_IOT_S9(lv_event_t * e);
extern lv_obj_t * ui_IOT_S9;
extern lv_obj_t * ui_IMG_S2_Bg_13;
extern lv_obj_t * ui_IMG_S2_Bg_14;
extern lv_obj_t * ui_Label__Connect2;
extern lv_obj_t * ui_Label_Ony_MQTT2;
extern lv_obj_t * ui_Panel_List_MQTT2;
extern lv_obj_t * ui_Label_MQTT5;
extern lv_obj_t * ui_IMG_MQTT2;
extern lv_obj_t * ui_Image3;
void ui_event_Panel_Return5(lv_event_t * e);
extern lv_obj_t * ui_Panel_Return5;
extern lv_obj_t * ui_Image_Return5;
void ui_event_Panel_Home5(lv_event_t * e);
extern lv_obj_t * ui_Panel_Home5;
extern lv_obj_t * ui_ImageHome5;
extern lv_obj_t * ui_Dropdown1;
void ui_event_BtnConnect(lv_event_t * e);
extern lv_obj_t * ui_BtnConnect;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_IOT_S10
void ui_IOT_S10_screen_init(void);
void ui_event_IOT_S10(lv_event_t * e);
extern lv_obj_t * ui_IOT_S10;
extern lv_obj_t * ui_IMG_S2_Bg_15;
extern lv_obj_t * ui_IMG_S2_Bg_16;
extern lv_obj_t * ui_Label__Connect3;
extern lv_obj_t * ui_Label_Ony_MQTT3;
extern lv_obj_t * ui_Panel_List_MQTT3;
extern lv_obj_t * ui_Label_MQTT4;
extern lv_obj_t * ui_IMG_MQTT3;
extern lv_obj_t * ui_Image1;
void ui_event_Panel_Return6(lv_event_t * e);
extern lv_obj_t * ui_Panel_Return6;
extern lv_obj_t * ui_Image_Return6;
void ui_event_Panel_Home6(lv_event_t * e);
extern lv_obj_t * ui_Panel_Home6;
extern lv_obj_t * ui_ImageHome6;
extern lv_obj_t * ui_Dropdown2;
void ui_event_BtnConnect1(lv_event_t * e);
extern lv_obj_t * ui_BtnConnect1;
extern lv_obj_t * ui_Label1;
void ui_event_Spinner2(lv_event_t * e);
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_img_bg_1_png);    // assets/IMG_BG_1.png
LV_IMG_DECLARE(ui_img_iot_png);    // assets/iot.png
LV_IMG_DECLARE(ui_img_img_arrow_right_png);    // assets/IMG_arrow_right.png
LV_IMG_DECLARE(ui_img_return_png);    // assets/return.png
LV_IMG_DECLARE(ui_img_service_png);    // assets/service.png
LV_IMG_DECLARE(ui_img_router_png);    // assets/Router.png
LV_IMG_DECLARE(ui_img_sound_png);    // assets/Sound.png
LV_IMG_DECLARE(ui_img_lamp_png);    // assets/Lamp.png
LV_IMG_DECLARE(ui_img_cameramonitor_png);    // assets/cameramonitor.png
LV_IMG_DECLARE(ui_img_socket_png);    // assets/socket.png
LV_IMG_DECLARE(ui_img_homepage_png);    // assets/homepage.png
LV_IMG_DECLARE(ui_img_mqtt_png);    // assets/MQTT.png
LV_IMG_DECLARE(ui_img_http_png);    // assets/http.png
LV_IMG_DECLARE(ui_img_ok_png);    // assets/ok.png
LV_IMG_DECLARE(ui_img_database_png);    // assets/database.png
LV_IMG_DECLARE(ui_img_circlefillgreen_png);    // assets/circlefillgreen.png
LV_IMG_DECLARE(ui_img_circlefillred_png);    // assets/circlefillred.png


LV_FONT_DECLARE(ui_font_Big_Number);
LV_FONT_DECLARE(ui_font_Bold_Font);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
